# Generated by Django 4.2.2 on 2023-06-26 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fut_pole', '0002_alter_owner_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fut_pole.owner'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='selected_date',
            field=models.DateField(),
        ),
    ]
